
# This file is automatically generated, you probably don't want to edit this

rfaOptions <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    "rfaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            indep = NULL,
            split = 75,
            ntree = 500, ...) {

            super$initialize(
                package='DTA',
                name='rfa',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..indep <- jmvcore::OptionVariables$new(
                "indep",
                indep)
            private$..split <- jmvcore::OptionNumber$new(
                "split",
                split,
                min=60,
                max=90,
                default=75)
            private$..ntree <- jmvcore::OptionNumber$new(
                "ntree",
                ntree,
                min=100,
                max=1000,
                default=500)

            self$.addOption(private$..dep)
            self$.addOption(private$..indep)
            self$.addOption(private$..split)
            self$.addOption(private$..ntree)
        }),
    active = list(
        dep = function() private$..dep$value,
        indep = function() private$..indep$value,
        split = function() private$..split$value,
        ntree = function() private$..ntree$value),
    private = list(
        ..dep = NA,
        ..indep = NA,
        ..split = NA,
        ..ntree = NA)
)

rfaResults <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Random Forest Analysis")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Random Forest Analysis"))}))

rfaBase <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    "rfaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'DTA',
                name = 'rfa',
                version = c(1,0,0),
                options = options,
                results = rfaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Random Forest Analysis
#'
#' 
#' @param data .
#' @param dep .
#' @param indep .
#' @param split .
#' @param ntree .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
rfa <- function(
    data,
    dep,
    indep,
    split = 75,
    ntree = 500) {

    if ( ! requireNamespace('jmvcore', quietly=TRUE))
        stop('rfa requires jmvcore to be installed (restart may be required)')

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(indep)) indep <- jmvcore::resolveQuo(jmvcore::enquo(indep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(indep), indep, NULL))


    options <- rfaOptions$new(
        dep = dep,
        indep = indep,
        split = split,
        ntree = ntree)

    analysis <- rfaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

